mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
	url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	# ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
from __future__ import unicode_literals

from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
    	return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
#from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

def index(request):
    
    #template = loader.get_template('polls/index.html')
    #template = 'polls/index.html'
    #context_object_name = 'latest_question_list'
    
    #def get_queryset(self):
    latest_question_list = Question.objects.order_by('-pub_date')

    #output = ', '.join([q.question_text for q in latest_question_list])
    #return HttpResponse(output)
    #return HttpResponse(template.render(context, request))
    return render(request, 'polls/index.html', {'latest_question_list': latest_question_list})

def detail(request, question_id):
    #return HttpResponse("You're looking at question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    #response = "You're looking at the results of question %s."
    question = get_object_or_404(Question, pk=question_id)

    total_votes = 0
    for choice in question.choice_set.all():
        total_votes += choice.votes;
        
    return render(request, 'polls/results.html', {'question': question, 'total_votes': total_votes})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% include "polls/pollsheader.html" %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class='content'>
<h2>{{ question.question_text }}</h2>
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<ul>
{% for choice in question.choice_set.all %}
	<li>
   	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
   	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
   	</li>
{% endfor %}
</ul>
<input type="submit" value="Vote" />
</form>
</div>

<div class="floatbottom"><a href="{% url 'polls:index' %}">Back to all polls</a></div>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% include "polls/pollsheader.html" %}

<div class='content'>
<h2>All polls</h2>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>

polls/templates/polls/pollsheader.html
<h1>Polls</h1>

polls/templates/polls/results.html
{% load static %}
{% load mathfilters %}
{% load temptags %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% include "polls/pollsheader.html" %}

<div class='content'>
<h2>{{ question.question_text }}</h2>

<ul>
{% for choice in question.choice_set.all %}
	{%	with numerator=choice.votes denominator=total_votes %}
    	<li>
    		<label>{{ choice.choice_text }}</label>
    		<progress max="100" value="{{numerator|div:denominator|mul:100|roundoff}}"></progress>
    		<div class="value-field">{{ numerator|div:denominator|mul:100|roundoff }}%</div>
    	</li>
    {% endwith %}
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>

<div class='floatbottom'><a href="{% url 'polls:index' %}">Back to all polls</a></div>